version: "3"
services:
  reverse-proxy:
    image: traefik:v2.9
    # Enables the web UI and tells Traefik to listen to docker
    command: --api.insecure=true --providers.docker
    ports:
      - 80:80
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  # App runner
  tran_eds:
    build: ./
    labels:
      - "traefik.http.routers.tran_eds.rule=Host(`medhead.localhost`) && PathPrefix(`/eds`)"
      - "traefik.http.routers.tran_eds.middlewares=eds-stripprefix"
      - "traefik.http.middlewares.eds-stripprefix.stripprefix.prefixes=/eds"
      - "traefik.http.services.tran_eds.loadbalancer.server.port=8080"

  # Redis dependency
  redis:
    image: redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - ./:/app